### ISSUE TITLE
As a devop I need a site for Dermaptera

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#10]
http://dermaptera.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- Heidi Hopkins
- Lesley Deem

**Comment by debpaul** [comment]
### preview tasks
- [x] home.md page text added
- [x] about.md page text added
- [x] config/yml files edited
  - [x] api.yml edited
  - [x] header.yml
  - [x] project.yml edited
  - [x] router.yml
- [x] send email to temp test site to manager/s (@hhopkins77 in this case)
### production tasks
- [x] config files editing
  - [x] api.yml
  - [x] tracker.yml
- [x] change where any images live (put into TW database)
### known issues
- [ ] add here as discovered

**Comment by hhopkins77** [comment]
This TaxonPage is ready for initial/test launch from my end. Please advise if there are issues that need my further attention.

**Comment by LocoDelAssembly** [comment]
Please confirm this is ready for deployment. Doing this will replace http://dermaptera.speciesfile.org/ with https://sfg-taxonpages.github.io/dermaptera/ and original SF will only be available in archive website.

**Comment by hhopkins77** [comment]
This TaxonPage is ready to go live. Please advise if anything further needs my attention. @mjy add Google analytics.

**Comment by mjy** [comment]
Analytics added.

**Comment by mjy** [comment]
Corrected analytics.

**Comment by mjy** [comment]
Site is live.  New issues on the individual repo.
