### ISSUE TITLE
As a devop I need a site for Coleorrhyncha

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#13]
http://coleorrhyncha.speciesfile.org

**Comment by mjy** [comment]
Talk to Sam about not making this a TP.  Very little curation effort/involvement.

**Comment by debpaul** [comment]
> Talk to Sam about not making this a TP. Very little curation effort/involvement.

When do we want to do this? And who will do this?

**Comment by debpaul** [comment]
**Project Admins**
- Heidi Hopkins
- Sam Heads

**Comment by hhopkins77** [comment]
This TaxonPage is ready for initial/test launch from my end. Please advise if there are issues that need my further attention. (I see we may not be creating TP for this).

**Comment by LocoDelAssembly** [comment]
Please confirm this is ready for deployment. Doing this will replace http://coleorrhyncha.speciesfile.org/ with https://sfg-taxonpages.github.io/coleorrhyncha/ and original SF will only be available in archive website.

**Comment by hhopkins77** [comment]
My understanding is that this page may be cancelled. Awaiting word. Update: from Ed, this TaxonPage is a go.

**Comment by hhopkins77** [comment]
This TaxonPage is ready to go live. Please advise if anything further needs my attention. @mjy add Google analytics.

**Comment by mjy** [comment]
Added analytics.

**Comment by mjy** [comment]
Site is live.  New issues on the individual repo.
