### ISSUE TITLE
As a devop I need a site for Grylloblattodea

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#17]
http://grylloblattodea.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- Heidi Hopkins

**Comment by debpaul** [comment]
### preview tasks
- [x] home.md page text added
- [x] about.md page text added
- [x] config/yml files edited
  - [x] api.yml edited
  - [x] copyright.yml
  - [x] header.yml
  - [x] metadata.yml
  - [x] project.yml edited
  - [x] router.yml
- [x] send email to temp test site to manager/s (Heidi @hhopkins77 this case)
### production tasks
- [ ] config files editing
  - [ ] api.yml
  - [x] tracker.yml
- [ ] change where any images live (put into TW database)
### known issues
- [ ] add here as discovered

**Comment by hhopkins77** [comment]
This TaxonPage is ready for initial/test launch from my end. Please advise if there are issues that need my further attention.

**Comment by LocoDelAssembly** [comment]
Please confirm this is ready for deployment. Doing this will replace http://grylloblattodea.speciesfile.org/ with https://sfg-taxonpages.github.io/grylloblattodea/ and original SF will only be available in archive website.

**Comment by hhopkins77** [comment]
This TaxonPage is ready to go live. Please advise if anything further needs my attention. @mjy add Google analytics.

**Comment by mjy** [comment]
Added analytics.

**Comment by mjy** [comment]
Live!  Followup issues should be added on the specific repo, and requests to refresh the site added newly here.

**Comment by hhopkins77** [comment]
This doesn't appear to be live, so I am reopening.

**Comment by hhopkins77** [comment]
It's live now!
