### ISSUE TITLE
As a devop I need a site for Plecoptera

### ISSUE THREAD

**Issue by mjy** [sfg-taxonpages/issues#2]
http://plecoptera.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- R. Edward DeWalt
- Heidi Hopkins

**Comment by debpaul** [comment]
### preview tasks
- [x] home.md page text added
- [x] about.md page text added
- [x] config/yml files to be edited
   - [x] api.yml edited
   - [ ] copyright.yml
   - [x] header.yml
   - [x] metadata.yml
   - [x] project.yml edited
   - [x] router.yml
- [ ] send email to temp test site to manager/s (Heidi and Lily in this case)
### production tasks
- [ ] config files editing
  - [ ] api.yml
  - [x] tracker.yml
- [ ] change where any images live (put into TW database)
### known issues
- [x] links to Perla and Illesia exist
- [ ] does Ed / do others want something else to happen for them?
- [ ] need to clarify copyright statements for both Perla and Illesia?
- [x] Home images stubbed JRF 30AUG23

**Comment by hhopkins77** [comment]
@mjy I have been through the Plecoptera TaxonPage and checked all links. I fixed one that wasn't working, but the other I found I'm not sure how to fix. It is the "Perla" button on the top banner. Could you fix or assign for fix? Or point me where to go and I can try to fix it.

**Comment by mjy** [comment]
Closing as complete.  New issues can address individual needs.
