### ISSUE TITLE
As a develop I need a site for Isoptera Catalog

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/issues#26]
Please create Repo for Isoptera Catalog. Many thanks.

**Comment by LocoDelAssembly** [comment]
Created at https://github.com/sfg-taxonpages/isoptera

**Comment by hhopkins77** [comment]
Thank you Hernán! This doesn't look like my other repos, which are CSS, not Vue. I can't find the Pages and Config files that I'm looking for. Can you help with this?

**Comment by LocoDelAssembly** [comment]
Sorry, forgot to push `setup` **first** then `main`, that caused to have `main` as default branch instead of `setup`. Please check again now.

**Comment by hhopkins77** [comment]
Yes, Pages and Config are there now!

**Comment by hhopkins77** [comment]
When you have a moment, please advise what to put for header_logo_url in the header.yml, and also what to put for the two URLs in project.yml?

**Comment by LocoDelAssembly** [comment]
@mjy is this going to be isoptera.speciesfile.org? About logo, is there an existing logo? Was the plan to have it as an image inside TW project @mjy ?

**Comment by mjy** [comment]
Unknown re logo availabilty. Logo can go inside TW (all images should I think).  Site is under discussion, hold on domains etc.

**Comment by hhopkins77** [comment]
@mjy Can we go ahead with this TaxonPage while waiting for the eventual merge, or would you prefer to hold off?

**Comment by mjy** [comment]
Added analytics.

**Comment by mjy** [comment]
Site is live.  New issues on the individual repo.
