### ISSUE TITLE
Link to archived site not working on all About pages

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/issues#29]
The link to the archived species file under History on the About page is not working on all Hopkins species files (except Isoptera, of course).

**Comment by mjy** [comment]
Dermaptera seems to be working.  Cockroch has 'blattodea' instead of  `cockroach`, didn't check the others, but maybe that is a clue for how to fix?

**Comment by hhopkins77** [comment]
RE Cockroach SF: That text is pulled from the project.yml which had the correct order name, as opposed to the common name entered. I have changed it to "cockroach" so it should work next time it is refreshed. The others do seem to be working now.
