### ISSUE TITLE
As a devop I need a site for Cockroach

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#4]
http://cockroach.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- George Beccaloni
- Heidi Hopkins

**Comment by debpaul** [comment]
### preview tasks
- [x] home.md page text added
- [x] about.md page text added
- [x] config/yml files edited
  - [x] api.yml edited
  - [x] copyright.yml
  - [x] header.yml
  - [x] metadata.yml
  - [x] project.yml edited
  - [x] router.yml
- [x] send email to temp test site to manager/s (@hhopkins77 in this case)
### production tasks
- [ ] config files editing
  - [ ] api.yml
  - [x] tracker.yml
- [ ] change where any images live (put into TW database)
### known issues
- [ ] add here as discovered

**Comment by hhopkins77** [comment]
This TaxonPage is nearly ready for initial/test launch from my end. Please advise as to whom should be the email contact in the project.yml. I have left it as G. Beccaloni, but I don't believe he is active in TW at all.

**Comment by LocoDelAssembly** [comment]
Please confirm this is ready for deployment. Doing this will replace http://cockroach.speciesfile.org/ with https://sfg-taxonpages.github.io/cockroach/ and original SF will only be available in archive website.

**Comment by hhopkins77** [comment]
This TaxonPage is ready to go live. Please advise if anything further needs my attention. @mjy add Google analytics.

**Comment by mjy** [comment]
Added analytics

**Comment by mjy** [comment]
Site is live.  New issues on the individual repo.  Needs to use the new gallery code.
