### ISSUE TITLE
As a devop I need a site for Phasmida

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#5]
http://phasmida.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- Paul D. Brock
- Daniel Otte
- Ed Baker
- Thies Büscher

**Comment by debpaul** [comment]
### preview tasks
- [x] home page text added
  - [ ] **try searching for** section needs editing: add taxa
- [x] about page text added
  - [x] about page text needs editing
- [x] config/yml files to be edited
  - [x] api.yml edited
  - [x] copyright.yml
  - [x] header.yml
  - [x] metadata.yml
  - [x] project.yml edited
  - [x] router.yml
- [x] send email with temp test site URL to manager/s (Paul Brock in this case)
### production tasks
- [ ] config files editing
  - [x] api.yml
  - [x] tracker.yml
  - [x] turn on analytics.yml (Paul does want this) @LocoDelAssembly @mjy 
- [ ] change where any images live (put into TW database)
### known issues
- [ ] Paul Brock needs to edit content (e. g. sample taxa, also history section). Email sent from @jrflood to Paul to offer help (and we can work on this together at next SF Curators' meeting). Maybe Thies would help too?

**Comment by LocoDelAssembly** [comment]
@mjy I have Analytics access for OSF only.

**Comment by mjy** [comment]
Added analytics.
