### ISSUE TITLE
As a devop I need a site for Aphid

### ISSUE THREAD

**Issue by jrflood** [sfg-taxonpages/issues#7]
http://aphid.speciesfile.org

**Comment by debpaul** [comment]
**Project Admins**
- Colin Favret

**Comment by debpaul** [comment]
### preview tasks
- [x] home page text added
- [x] about page text added
- [x] config/yml files to be edited
  - [x] api.yml edited
  - [x] copyright.yml
  - [x] header.yml
  - [x] metadata.yml
  - [x] project.yml edited
  - [x] router.yml
- [x] send email with temp test site URL to manager/s (Colin Favret in this case)
### production tasks
- [ ] config files editing
  - [ ] api.yml
  - [ ] tracker.yml
- [ ] change where any images live (put into TW database)
### known issues
- [ ] @ColinFavret needs to edit content (e. g. sample taxa, also history section). Email sent from @debpaul to Colin to offer help (one-on-one or at next SF Curators' meeting)
- [x] aphid map data not in database @jrflood to have a look-see

**Comment by mjy** [comment]
Aphid map data will not be migrated, per conversation with Colin.  It's small in quantity and can be manually redone.  Was for fossil data only.

**Comment by mjy** [comment]
Site is live.
